services:

    web:

      build:
        args:
          - build_env=production
        context: .
        target: production

      env_file:
        - secrets.env

      environment:
        FLASK_APP: core_app.factory
        FLASK_ENV: production

      ports:
        - 8000:8000

    rabbitmq:

      image: rabbitmq

    # redis:
    #
    #   image: redis:alpine
