name: Build

on:

  push:
    branches: [main]

jobs:

  build_image:

    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Get current latest image id
        run: >
          python3 <<EOF
          import requests, json
          url = 'https://api.github.com/user/packages/container/${{ github.event.repository.name }}/versions'
          headers = dict(
              Authorization='token ${{ secrets.GHCR_PAT }}',
              Accept='application/vnd.github.v3+json'
          )
          resp = requests.get(url, headers=headers)
          print(f'IMAGE_EXISTED={1 if resp.status_code == 200 else 0}')
          if resp.status_code == 200:
              latest_id = resp.json()[0]['id']
              print(f'LATEST_IMAGE_ID={latest_id}')
          EOF
          >> ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Allow scripts to be executed
        run: chmod -R +x scripts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Append downcase repo path to the environment
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Build image & push to GHCR
        uses: docker/build-push-action@v2
        with:
          build-args:
            -build_env=production
          context: .
          target: production
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest

      - name: Delete previous image
        if: ${{ env.IMAGE_EXISTED == 1}}
        run: >
          wget
          --header="Authorization: token ${{ secrets.GHCR_PAT }}"
          --header="Accept: application/vnd.github.v3+json"
          --method=DELETE
          -nv
          -O - https://api.github.com/user/packages/container/${{ github.event.repository.name }}/versions/${{ env.LATEST_IMAGE_ID }}
